before:
  hooks:
    - go mod download

changelog:
  sort: desc
  use: github
  filters:
    exclude:
    - Merge branch
    - Merge pull request

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
    main: ./
    binary: symfony
    ldflags: -s -w -X 'main.channel={{ if index .Env "AUTOUPDATE_CHANNEL" }}{{ .Env.AUTOUPDATE_CHANNEL }}{{ else }}dev{{ end }}' -X 'main.buildDate={{ .Date }}' -X 'main.version={{ .Version }}'
    flags:
      - -trimpath

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

# create a source tarball
# https://goreleaser.com/customization/source/
source:
  enabled: true

snapshot:
  name_template: "next"

universal_binaries:
  - replace: true
    name_template: symfony

# sign all artifacts
# https://goreleaser.com/customization/sign
signs:
- cmd: cosign
  env:
  - COSIGN_EXPERIMENTAL=1
  certificate: '${artifact}.pem'
  args:
    - sign-blob
    - '--output-certificate=${certificate}'
    - '--output-signature=${signature}'
    - '${artifact}'
  artifacts: all
  output: true

release:
  footer: |
    **Full Changelog**: https://github.com/symfony-cli/symfony-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - tap:
      owner: symfony-cli
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Fabien Potencier
      email: fabien@symfony.com
    folder: Formula
    goarm: "7"
    homepage: https://symfony.com
    description: Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
    license: AGPL-3.0
    test: |
      system "#{bin}/symfony version"
    dependencies:
    - name: git
      type: optional
    install: |-
      bin.install "symfony"
    service: |-
      run ["#{bin}/symfony", "local:proxy:start", "--foreground"]
      keep_alive true

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://symfony.com
    description: Symfony CLI helps Symfony developers manage projects, from local code to remote infrastructure
    maintainer: Fabien Potencier <fabien@symfony.com>
    license: AGPL-3.0
    vendor: Symfony
    formats:
    - apk
    - deb
    - rpm
    recommends:
    - git
